### ISSUE TITLE
Difference between bayesynergy and synergysplines

### ISSUE THREAD

**Issue by wleoncio** [ltronneb/bayesynergy#2]
What is the difference between this package and [synergysplines](https://github.com/ocbe-uio/synergysplines)? Their descriptions are almost identical. If I understood correctly the latter is explicitly following the experiments "described in Cremaschi et. al (2019)", but there is no further information on this one.

**Comment by ltronneb** [comment]
Hey,

A bit of a long story. Me and Andrea (Cremaschi) wrote what is now called
synergysplines last summer. It was based on the 2019 paper you are linking
to, but also extended some models to include a new formulation based on
Gaussian Processes -- using a Gibbs sampler written in C++. Over the
winter, to accommodate certain computational issues, I rewrote the sampler
to use a Stan formulation, which makes significant speedups and other
fixes. We are writing a new paper specifically about this package now and
the new model formulation.

Initially this was all one single package, but it was exceedingly difficult
to keep both Stan code and C++ code around due to compilation issues (on
Windows specifically), so finally we decided to split the thing up. So now
synergysplines contains the original spline version with Gibbs that Andrea
implemented, and bayesynergy is the GP formulation written in Stan using
HMC.

Leiv




tor. 29. okt. 2020 kl. 09:46 skrev Waldir Leoncio <notifications@github.com

**Comment by wleoncio** [comment]
Got it, I think I remember you mentioned this during some lunch conversation of ours. Is it OK if I add this info to the [README](https://github.com/ocbe-uio/bayesynergy/blob/master/README.md)? Otherwise I might end up asking this again because my memory is not great. 🤕

**Comment by ltronneb** [comment]
Sure, but keep in mind that this package is very much a continuation and improvement on the synergysplines. We basically needed a place to store that code for when the paper is resubmitted.

**Comment by wleoncio** [comment]
Sure, looks like it's all stored in the proper places. I just wish to link both projects.

Thank you for the explanation, Leiv, I'll close the issue now.
